### ISSUE TITLE
What is the expected running time of the training script?

### ISSUE THREAD

**Issue by Moreland-cas** [hu-hy17/HOIC#2]

**Comment by hu-hy17** [comment]
It depends on the hardware you use. The CPU and the number of processors influence the time of sampling while the GPU influences the time of network training.

I have tested on a 16-core AMD EPYC 9654 CPU and an NVIDIA 4090 GPU and it takes about 48 hours to train 4000 epochs.  (I set the max epoch number to 20000 in the default settings but usually 4000~5000 epochs is enough).
